openapi: 3.0.0
info:
  title: Social App
  description: Our First Social App- Prayas
  version: 1.0.1
servers:
  - url: http://localhost:4000/api/v1
    description: localhost version of our app
  - url: https://localhost:4000/api/v1
    description: Dummy API Url, it doesn't work
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer